### ISSUE TITLE
Consider knitr::opts_chunk$set(collapse = TRUE)

### ISSUE THREAD

**Issue by wlandau** [krlmlr/drake-pitch#1]
For example, in [slide 5](https://krlmlr.github.io/drake-pitch/#5). This converts the automatic double-spacing to single-spacing in the output of `message()`. I use it in `drake`'s vignettes.

**Comment by wlandau** [comment]
Related: ropensci/drake#164. I think we'll need to wait for `ansistrings` to mature for that bit. Really looking forward `make()`'s `crayon` colors to show up in the vignettes.

**Comment by krlmlr** [comment]
Thanks, I was wondering about the double-spacing but ultimately didn't care enough.
