### ISSUE TITLE
Slide 11: consider adding a comment where the command for `data` changed.

### ISSUE THREAD

**Issue by wlandau** [krlmlr/drake-pitch#2]

**Comment by krlmlr** [comment]
Tried this, but couldn't make it work. Maybe you have better luck? 

@yihui: Is there a way to highlight lines by specifying their number in *xaringan*? I want to highlight lines 7 and 10 in the source code of https://krlmlr.github.io/drake-pitch/#11.

**Comment by yihui** [comment]
No, not by line numbers. WIth the dev version of xaringan, you can use the trailing comment `#<<` to highlight lines: https://slides.yihui.name/xaringan/#29

**Comment by krlmlr** [comment]
Thanks, works as advertised!
