### ISSUE TITLE
Increase the widths of visNetwork graphs in the slides.

### ISSUE THREAD

**Issue by wlandau** [krlmlr/drake-pitch#3]
I think the legends could be farther away from the graphs. `visNetwork()` allows you to control the `width` and `height`, and `vis_drake_graph()` passes args to `visNetwork()` through `...`:

```r
vis_drake_graph(
  config,
  targets_only = TRUE,
  width = "100%",
  height = "500px"
)
```

**Comment by krlmlr** [comment]
Would you mind suggesting a pull request? You can use `make` to update `docs/index.html`.
